#!/usr/bin/env bash
# ------------------------------------------------------------
# Script     :
# Descrição  :
# Versão     : 1.0
# Autor      : Marconi S. de Jesus <marconi.developer@outlook.com.br>
# Licença    : GNU/GPL v3.0
# Data       : 10/02/2023
# ------------------------------------------------------------
# Uso:
# ------------------------------------------------------------
# if ls txt* &> /dev/null; then
#   echo "Status $? - Verdadeiro"
# elif ls test* &> /dev/null; then
#   echo Só achei o arquivo test*
# else
#   echo "Status $? - Falso"
# fi

#fruta=laranja
#if [[ $fruta = banana ]]; then
#  echo "Status $? - Verdadeiro"
#  echo "O nome da fruta é $fruta, não banana."
#else
#  echo "Status $? - Falso"
#  echo "O nome da fruta não é banana, é sim $fruta."
#fi

# teste=0
# if ((teste)); then
#  echo Verdadero
# else 
#  echo Falso
# fi


fruta=$1

case $fruta in 
   banana|laranja) echo "$fruta é amarela" ;;
  abacate|uva) echo "$fruta é verde"       ;;
  morango) echo "$fruta é vermelha"        ;;
        *) echo "Não sei a cor da fruta $1";;
esac

exit 0
