#!/usr/bin/env bash
# ------------------------------------------------------------
# Script     :
# Descrição  :
# Versão     : 1.0
# Autor      : Marconi S. de Jesus <marconi.developer@outlook.com.br>
# Licença    : GNU/GPL v3.0
# Data       : 10/02/2023
# ------------------------------------------------------------
# Uso:
# ------------------------------------------------------------
clear

PS3=$'\nEscolha uma fruta: '
select fruta in banana laranja abacaxi; do
  echo $fruta
  break
done 

exit 0
