#!/usr/bin/env bash
# ------------------------------------------------------------
# Script     : condicionais
# Descrição  : exemplos de testes de exprossoẽs condicionais
# Versão     : 1.0
# Autor      : Marconi S. de Jesus <marconi.developer@outlook.com.br>
# Licença    : GNU/GPL v3.0
# Data       : 04/02/2023
# ------------------------------------------------------------
# Uso: ./condicionais ou /caminho/condicionais
# ------------------------------------------------------------

clear 

# Mensagem...

echo "O objtivo desse script é comparar o seu núemro com o número '5'."

read -p "Entre com um número de 1 a 10: " numero

# Tratar erros...
[[ ! $numero =~ ^[0-9]+$ ]] && echo "Err: não é um número" && exit 1 

[[ $numero -gt 10 || $numero -lt 0 ]] && echo "Err: Número inválido" && exit 1

# Respostas normais...
[[ $numero -eq 5 ]] && echo "Seu número é igual a 5!" && exit 0

[[ $numero -lt 5 ]] && echo "Seu número é menor que 5" && exit 0

[[ $numero -gt 5 ]] && echo "Seu número é maior que 5" && exit 0
