#!/usr/bin/env bash
# ------------------------------------------------------------
# Script     :
# Descrição  :
# Versão     : 1.0
# Autor      : Marconi S. de Jesus <marconi.developer@outlook.com.br>
# Licença    : GNU/GPL v3.0
# Data       : 10/02/2023
# ------------------------------------------------------------
# Uso:
# ------------------------------------------------------------

echo "---------------"

for n in {1..5}; do
  >> arquivo$n
done 

ls -1 arq*
echo "---------------"

for f in arquivo*; do
  mv $f $f.txt
done

ls -1 arq*
echo "---------------"
