#!/usr/bin/env bash
# ------------------------------------------------------------
# Script     :
# Descrição  :
# Versão     : 1.0
# Autor      : Marconi S. de Jesus <marconi.developer@outlook.com.br>
# Licença    : GNU/GPL v3.0
# Data       : 10/02/2023
# ------------------------------------------------------------
# Uso:
# ------------------------------------------------------------
compras='pão
leite
ovos
margarina
café'

for p in $compras; do
  echo $p
done

echo "==============="  
compras=$'pão\nleite\novos\nmargarina\ncafé'

for p in $compras; do
  echo $p
done

