#!/usr/bin/env bash
# ------------------------------------------------------------
# Script     :
# Descrição  :
# Versão     : 1.0
# Autor      : Marconi S. de Jesus <marconi.developer@outlook.com.br>
# Licença    : GNU/GPL v3.0
# Data       : 10/02/2023
# ------------------------------------------------------------
# Uso:
# ------------------------------------------------------------
alunos=(João Maria "Luis Carlos")

echo "Nomes"
for nome in "${alunos[@]}"; do
  echo $nome
done

echo "==============="
echo "Indice"

for indice in ${!alunos[@]}; do
  echo $indice
done

echo "==============="
echo "Nome com Indice"

for i in ${!alunos[@]}; do 
  echo "aluno $i --> ${alunos[$i]}"
done
