#!/usr/bin/env bash
# ------------------------------------------------------------
# Script     :
# Descrição  :
# Versão     : 1.0
# Autor      : Marconi S. de Jesus <marconi.developer@outlook.com.br>
# Licença    : GNU/GPL v3.0
# Data       : 10/02/2023
# ------------------------------------------------------------
# Uso:
# ------------------------------------------------------------

echo "==============="
echo "Interrompendo com break"

for n in {1..10}; do 
  [[ $n -gt 5 ]] && break || echo $n
done 

echo "==============="
echo "Interrompendo com continue"

for n in {1..10}; do
  [[ $n -lt 6 && continue ]] || echo $n
done

